#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
RESOURCES="$DIR/../Resources"
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
OUTPUT=$(/usr/bin/python3 "$RESOURCES/switch_mouse.py" "$@" 2>&1)
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
    ESCAPED_OUTPUT=$(echo "$OUTPUT" | sed 's/"/\\"/g')
    osascript -e "display alert \"Mouse Switch Failed\" message \"$ESCAPED_OUTPUT\n\nMake sure the pairing button underneath the mouse is blinking rapidly and try again.\""
fi
exit $EXIT_CODE
